-- ADD PRIMARY KEYS
ALTER TABLE SCHOOL ADD PRIMARY KEY (ID);
ALTER TABLE MODULE ADD PRIMARY KEY (ID);
ALTER TABLE TUTOR ADD PRIMARY KEY (ID);
ALTER TABLE BOOK ADD PRIMARY KEY (ISBN);
ALTER TABLE COURSE ADD PRIMARY KEY (ID);
ALTER TABLE COPY ADD PRIMARY KEY (ID);
ALTER TABLE STUDENT ADD PRIMARY KEY (ID);
ALTER TABLE COURSE_MODULE ADD PRIMARY KEY (ID);
ALTER TABLE ASSESSMENT ADD PRIMARY KEY (ID);
ALTER TABLE STUDENT_ASSESSMENT ADD PRIMARY KEY (STUDENT_ID, ASSESSMENT_ID);
ALTER TABLE LOAN ADD PRIMARY KEY (ID);
ALTER TABLE TUTOR_C_MODULE ADD PRIMARY KEY (TUTOR_ID, COURSE_MODULE_ID);

-- ADD FOREIGN KEYS
ALTER TABLE COURSE ADD FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(ID) ON DELETE CASCADE;
ALTER TABLE STUDENT ADD FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) ON DELETE CASCADE;
ALTER TABLE COPY ADD FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE;
ALTER TABLE COURSE_MODULE ADD FOREIGN KEY (MODULE_ID) REFERENCES MODULE(ID) ON DELETE CASCADE;
ALTER TABLE COURSE_MODULE ADD FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) ON DELETE CASCADE;
ALTER TABLE ASSESSMENT ADD FOREIGN KEY (COURSE_MODULE_ID)
                            REFERENCES COURSE_MODULE(ID) ON DELETE CASCADE;
ALTER TABLE STUDENT_ASSESSMENT ADD FOREIGN KEY (ASSESSMENT_ID)
                            REFERENCES ASSESSMENT(ID) ON DELETE CASCADE;
ALTER TABLE STUDENT_ASSESSMENT ADD FOREIGN KEY (STUDENT_ID)
                            REFERENCES STUDENT(ID) ON DELETE CASCADE;
ALTER TABLE LOAN ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID) ON DELETE CASCADE;
ALTER TABLE LOAN ADD FOREIGN KEY (TUTOR_ID) REFERENCES TUTOR(ID) ON DELETE CASCADE;
ALTER TABLE LOAN ADD FOREIGN KEY (COPY_ID) REFERENCES COPY(ID) ON DELETE CASCADE;
ALTER TABLE TUTOR_C_MODULE ADD FOREIGN KEY (COURSE_MODULE_ID)
                            REFERENCES COURSE_MODULE(ID) ON DELETE CASCADE;
ALTER TABLE TUTOR_C_MODULE ADD FOREIGN KEY (TUTOR_ID)
                            REFERENCES TUTOR(ID) ON DELETE CASCADE;


-- CONSTRAINTS
---- UNIQUE
ALTER TABLE TUTOR ADD CONSTRAINT UNIQUE_TUTOR_EMAIL UNIQUE (EMAIL);
ALTER TABLE STUDENT ADD CONSTRAINT UNIQUE_STUDENT_EMAIL UNIQUE (EMAIL);
ALTER TABLE COURSE ADD CONSTRAINT UNIQUE_COURSE UNIQUE(COURSE_NAME);
---- CHECKS (only titles)
ALTER TABLE TUTOR ADD CONSTRAINT CHECK_TUTOR_TITLE CHECK (TITLE IN
  ('Associate Lecturer',
  'Lecturer',
  'Senior Lecturer',
  'Associate Professor',
  'Professor')
);
ALTER TABLE STUDENT ADD CONSTRAINT CHECK_STUDENT_TITLE CHECK (TITLE IN
  ('MRS',
  'MISS',
  'MR',
  'DR')
);
---- UPPER CASE (only people names)
ALTER TABLE TUTOR ADD CONSTRAINT CHECK_UPPER1 CHECK (UPPER(FIRST_NAME) = FIRST_NAME);
ALTER TABLE TUTOR ADD CONSTRAINT CHECK_UPPER2 CHECK (UPPER(LAST_NAME) = LAST_NAME);
ALTER TABLE BOOK ADD CONSTRAINT CHECK_UPPER3 CHECK (UPPER(AUTHOR) = AUTHOR);
ALTER TABLE COURSE ADD CONSTRAINT CHECK_UPPER4 CHECK (UPPER(PRESIDENT) = PRESIDENT);
ALTER TABLE STUDENT ADD CONSTRAINT CHECK_UPPER5 CHECK (UPPER(FIRST_NAME) = FIRST_NAME);
ALTER TABLE STUDENT ADD CONSTRAINT CHECK_UPPER6 CHECK (UPPER(LAST_NAME) = LAST_NAME);

-- ADD
ALTER TABLE TUTOR ADD COUNTRY VARCHAR2(30);
-- DEFAULT
ALTER TABLE TUTOR MODIFY COUNTRY DEFAULT 'Greece';
-- MODIFY
ALTER TABLE STUDENT_ASSESSMENT MODIFY GRADE NUMERIC(4,2);

ALTER TABLE STUDENT_ASSESSMENT ADD CONSTRAINT POSITIVE_ONLY CHECK (GRADE >= 0);