
-- Here order doesn't matter, as long as constraints are deleted first
ALTER TABLE STUDENT_ASSESSMENT DROP CONSTRAINT POSITIVE_ONLY;
ALTER TABLE TUTOR DROP CONSTRAINT UNIQUE_TUTOR_EMAIL;
ALTER TABLE STUDENT DROP CONSTRAINT UNIQUE_STUDENT_EMAIL;
ALTER TABLE COURSE DROP CONSTRAINT UNIQUE_COURSE;
ALTER TABLE TUTOR DROP CONSTRAINT CHECK_TUTOR_TITLE;
ALTER TABLE STUDENT DROP CONSTRAINT CHECK_STUDENT_TITLE;
ALTER TABLE TUTOR DROP CONSTRAINT CHECK_UPPER1;
ALTER TABLE TUTOR DROP CONSTRAINT CHECK_UPPER2;
ALTER TABLE BOOK DROP CONSTRAINT CHECK_UPPER3;
ALTER TABLE COURSE DROP CONSTRAINT CHECK_UPPER4;
ALTER TABLE STUDENT DROP CONSTRAINT CHECK_UPPER5;
ALTER TABLE STUDENT DROP CONSTRAINT CHECK_UPPER6;

-- Here order matters; it must be the inverse of creation
DROP TABLE TUTOR_C_MODULE;
DROP TABLE LOAN;
DROP TABLE STUDENT_ASSESSMENT;
DROP TABLE ASSESSMENT;
DROP TABLE COURSE_MODULE;
DROP TABLE STUDENT;
DROP TABLE COPY;
DROP TABLE COURSE;
DROP TABLE BOOK;
DROP TABLE TUTOR;
DROP TABLE MODULE;
DROP TABLE SCHOOL;

DROP SEQUENCE PRIMARY_STUDENTS_KEY;
